// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxo2nHU40GbdNRAV5ikKrCag0XwOlMpgE',
    appId: '1:980261491778:web:64db3644512113ab0c49db',
    messagingSenderId: '980261491778',
    projectId: 'kk-nutrition-cf0cc',
    authDomain: 'kk-nutrition-cf0cc.firebaseapp.com',
    databaseURL: 'https://kk-nutrition-cf0cc-default-rtdb.firebaseio.com',
    storageBucket: 'kk-nutrition-cf0cc.appspot.com',
    measurementId: 'G-S3YT9EXBJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp6SNlYneOB6a9qnjZmhvS7x8HplUEG6M',
    appId: '1:980261491778:android:1c760092024080620c49db',
    messagingSenderId: '980261491778',
    projectId: 'kk-nutrition-cf0cc',
    databaseURL: 'https://kk-nutrition-cf0cc-default-rtdb.firebaseio.com',
    storageBucket: 'kk-nutrition-cf0cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlIhrokQxcdSiOnAakjQw_D3Afc7g0_uQ',
    appId: '1:980261491778:ios:043f647b357bfc580c49db',
    messagingSenderId: '980261491778',
    projectId: 'kk-nutrition-cf0cc',
    databaseURL: 'https://kk-nutrition-cf0cc-default-rtdb.firebaseio.com',
    storageBucket: 'kk-nutrition-cf0cc.appspot.com',
    iosClientId: '980261491778-i5uremm2mf20ngv380v3n1grmnp46h6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.kaylaknowsNutrition',
  );
}
